Skylark (Sketching Library): skylark::sketch::sketch_transform_t< InputMatrixType, OutputMatrixType > Class Template Reference
skylark::sketch::sketch_transform_t< InputMatrixType, OutputMatrixType > Class Template Reference
#include <sketch_transform.hpp>
Public Member Functions
virtual void apply (const InputMatrixType &A, OutputMatrixType &sketch_of_A, columnwise_tag dimension) const =0
virtual void apply (const InputMatrixType &A, OutputMatrixType &sketch_of_A, rowwise_tag dimension) const =0
virtual int get_N () const =0
virtual int get_S () const =0
virtual const
sketch_transform_data_t * get_data () const =0
boost::property_tree::ptree to_ptree () const
virtual ~sketch_transform_t ()
Static Public Member Functions
static sketch_transform_t * from_ptree (const boost::property_tree::ptree &pt)
Detailed Description
template<typename InputMatrixType, typename OutputMatrixType = InputMatrixType>
class skylark::sketch::sketch_transform_t< InputMatrixType, OutputMatrixType >
Abstract base class for all sketch transforms.
Definition at line 16 of file sketch_transform.hpp.
Constructor & Destructor Documentation
template<typename InputMatrixType, typename OutputMatrixType = InputMatrixType> virtual skylark::sketch::sketch_transform_t< InputMatrixType, OutputMatrixType >::~sketch_transform_t () [inline, virtual]
Definition at line 35 of file sketch_transform.hpp.
Member Function Documentation
template<typename InputMatrixType, typename OutputMatrixType = InputMatrixType> virtual void skylark::sketch::sketch_transform_t< InputMatrixType, OutputMatrixType >::apply (const InputMatrixType & A, OutputMatrixType & sketch_of_A, columnwise_tag dimension) const [pure virtual]
Implemented in skylark::sketch::FJLT_t< InputMatrixType, OutputMatrixType >, and skylark::sketch::PPT_t< InputMatrixType, OutputMatrixType >.
Referenced by BlockADMMSolver< T >::train().
template<typename InputMatrixType, typename OutputMatrixType = InputMatrixType> virtual void skylark::sketch::sketch_transform_t< InputMatrixType, OutputMatrixType >::apply (const InputMatrixType & A, OutputMatrixType & sketch_of_A, rowwise_tag dimension) const [pure virtual]
Implemented in skylark::sketch::FJLT_t< InputMatrixType, OutputMatrixType >, and skylark::sketch::PPT_t< InputMatrixType, OutputMatrixType >.
template<typename IT , typename OT > sketch_transform_t< IT, OT > * skylark::sketch::sketch_transform_t< IT, OT >::from_ptree (const boost::property_tree::ptree & pt) [static]
Definition at line 49 of file sketch_add.hpp.
References AUTO_LOAD_DISPATCH, skylark::sketch::c::CT, skylark::sketch::c::CWT, skylark::sketch::c::ExpSemigroupRLT, skylark::sketch::c::FastGaussianRFT, skylark::sketch::c::FJLT, skylark::sketch::c::GaussianRFT, skylark::sketch::c::JLT, skylark::sketch::c::LaplacianRFT, skylark::sketch::c::MMT, skylark::sketch::c::PPT, SKYLARK_THROW_EXCEPTION, and skylark::sketch::c::WZT.
Referenced by skylark::ml::model_t< InputType, OutputType >::build_from_ptree().
template<typename InputMatrixType, typename OutputMatrixType = InputMatrixType> virtual const sketch_transform_data_t* skylark::sketch::sketch_transform_t< InputMatrixType, OutputMatrixType >::get_data () const [pure virtual]
Implemented in skylark::sketch::hash_transform_t< elem::DistMatrix< ValueType, ColDist, RowDist >, elem::DistMatrix< ValueType, elem::STAR, elem::STAR >, IdxDistributionType, ValueDistribution >, skylark::sketch::FJLT_t< elem::DistMatrix< ValueType, ColDist, elem::STAR >, elem::DistMatrix< ValueType, elem::STAR, elem::STAR > >, skylark::sketch::LaplacianRFT_t< InputMatrixType, OutputMatrixType >, skylark::sketch::ExpSemigroupRLT_t< InputMatrixType, OutputMatrixType >, skylark::sketch::GaussianRFT_t< InputMatrixType, OutputMatrixType >, skylark::sketch::FastGaussianRFT_t< InputMatrixType, OutputMatrixType >, skylark::sketch::FJLT_t< elem::DistMatrix< ValueType, ColDist, elem::STAR >, elem::Matrix< ValueType > >, skylark::sketch::WZT_t< InputMatrixType, OutputMatrixType >, skylark::sketch::CT_t< InputMatrixType, OutputMatrixType >, skylark::sketch::JLT_t< InputMatrixType, OutputMatrixType >, skylark::sketch::MMT_t< InputMatrixType, OutputMatrixType >, skylark::sketch::CWT_t< InputMatrixType, OutputMatrixType >, skylark::sketch::FJLT_t< InputMatrixType, OutputMatrixType >, and skylark::sketch::PPT_t< InputMatrixType, OutputMatrixType >.
Referenced by skylark::sketch::sketch_transform_t< elem::DistMatrix< ValueType, ColDist, RowDist >, elem::DistMatrix< ValueType, elem::STAR, elem::STAR > >::to_ptree().
template<typename InputMatrixType, typename OutputMatrixType = InputMatrixType> virtual int skylark::sketch::sketch_transform_t< InputMatrixType, OutputMatrixType >::get_N () const [pure virtual]
Get input dimension
Implemented in skylark::sketch::hash_transform_t< elem::DistMatrix< ValueType, ColDist, RowDist >, elem::DistMatrix< ValueType, elem::STAR, elem::STAR >, IdxDistributionType, ValueDistribution >, skylark::sketch::FJLT_t< elem::DistMatrix< ValueType, ColDist, elem::STAR >, elem::DistMatrix< ValueType, elem::STAR, elem::STAR > >, skylark::sketch::LaplacianRFT_t< InputMatrixType, OutputMatrixType >, skylark::sketch::ExpSemigroupRLT_t< InputMatrixType, OutputMatrixType >, skylark::sketch::GaussianRFT_t< InputMatrixType, OutputMatrixType >, skylark::sketch::FastGaussianRFT_t< InputMatrixType, OutputMatrixType >, skylark::sketch::FJLT_t< elem::DistMatrix< ValueType, ColDist, elem::STAR >, elem::Matrix< ValueType > >, skylark::sketch::WZT_t< InputMatrixType, OutputMatrixType >, skylark::sketch::CT_t< InputMatrixType, OutputMatrixType >, skylark::sketch::JLT_t< InputMatrixType, OutputMatrixType >, skylark::sketch::MMT_t< InputMatrixType, OutputMatrixType >, skylark::sketch::CWT_t< InputMatrixType, OutputMatrixType >, skylark::sketch::FJLT_t< InputMatrixType, OutputMatrixType >, and skylark::sketch::PPT_t< InputMatrixType, OutputMatrixType >.
template<typename InputMatrixType, typename OutputMatrixType = InputMatrixType> virtual int skylark::sketch::sketch_transform_t< InputMatrixType, OutputMatrixType >::get_S () const [pure virtual]
Get output dimension
Implemented in skylark::sketch::hash_transform_t< elem::DistMatrix< ValueType, ColDist, RowDist >, elem::DistMatrix< ValueType, elem::STAR, elem::STAR >, IdxDistributionType, ValueDistribution >, skylark::sketch::FJLT_t< elem::DistMatrix< ValueType, ColDist, elem::STAR >, elem::DistMatrix< ValueType, elem::STAR, elem::STAR > >, skylark::sketch::LaplacianRFT_t< InputMatrixType, OutputMatrixType >, skylark::sketch::ExpSemigroupRLT_t< InputMatrixType, OutputMatrixType >, skylark::sketch::GaussianRFT_t< InputMatrixType, OutputMatrixType >, skylark::sketch::FastGaussianRFT_t< InputMatrixType, OutputMatrixType >, skylark::sketch::FJLT_t< elem::DistMatrix< ValueType, ColDist, elem::STAR >, elem::Matrix< ValueType > >, skylark::sketch::WZT_t< InputMatrixType, OutputMatrixType >, skylark::sketch::CT_t< InputMatrixType, OutputMatrixType >, skylark::sketch::JLT_t< InputMatrixType, OutputMatrixType >, skylark::sketch::MMT_t< InputMatrixType, OutputMatrixType >, skylark::sketch::CWT_t< InputMatrixType, OutputMatrixType >, skylark::sketch::FJLT_t< InputMatrixType, OutputMatrixType >, and skylark::sketch::PPT_t< InputMatrixType, OutputMatrixType >.
template<typename InputMatrixType, typename OutputMatrixType = InputMatrixType> boost::property_tree::ptree skylark::sketch::sketch_transform_t< InputMatrixType, OutputMatrixType >::to_ptree () const [inline]
Definition at line 31 of file sketch_transform.hpp.
The documentation for this class was generated from the following files:
/var/lib/jenkins/jobs/Skylark/workspace/sketch/sketch_transform.hpp
/var/lib/jenkins/jobs/Skylark/workspace/sketch/sketch_add.hpp