Skylark (Sketching Library): /var/lib/jenkins/jobs/Skylark/workspace/ml/run.hpp File Reference
/var/lib/jenkins/jobs/Skylark/workspace/ml/run.hpp File Reference
#include "BlockADMM.hpp"
#include "options.hpp"
#include "io.hpp"
#include "../base/context.hpp"
#include "model.hpp"
Functions
template<class InputType >
BlockADMMSolver< InputType > * GetSolver (skylark::base::context_t &context, const hilbert_options_t &options, int dimensions)
void ShiftForLogistic (LocalMatrixType &Y)
template<class InputType , class LabelType >
int run (const boost::mpi::communicator &comm, skylark::base::context_t &context, hilbert_options_t &options)
Function Documentation
template<class InputType > BlockADMMSolver<InputType>* GetSolver (skylark::base::context_t & context, const hilbert_options_t & options, int dimensions)
Definition at line 13 of file run.hpp.
References hilbert_options_t::cachetransforms, EXPSEMIGROUP, GAUSSIAN, HINGE, hilbert_options_t::kernel, hilbert_options_t::kernelparam, hilbert_options_t::kernelparam2, hilbert_options_t::kernelparam3, L1, L2, LAD, hilbert_options_t::lambda, LAPLACIAN, LINEAR, LOGISTIC, hilbert_options_t::lossfunction, hilbert_options_t::MAXITER, hilbert_options_t::numfeaturepartitions, hilbert_options_t::numthreads, POLYNOMIAL, hilbert_options_t::randomfeatures, hilbert_options_t::regularizer, hilbert_options_t::regularmap, hilbert_options_t::rho, BlockADMMSolver< T >::set_cache_transform(), BlockADMMSolver< T >::set_maxiter(), BlockADMMSolver< T >::set_nthreads(), BlockADMMSolver< T >::set_rho(), BlockADMMSolver< T >::set_tol(), SQUARED, and hilbert_options_t::tolerance.
template<class InputType , class LabelType > int run (const boost::mpi::communicator & comm, skylark::base::context_t & context, hilbert_options_t & options)
Definition at line 153 of file run.hpp.
References skylark::ml::model_t< InputType, OutputType >::evaluate(), hilbert_options_t::fileformat, skylark::ml::model_t< InputType, OutputType >::get_input_size(), skylark::ml::model_t< InputType, OutputType >::get_num_outputs(), skylark::base::Height(), LOGISTIC, hilbert_options_t::lossfunction, hilbert_options_t::modelfile, hilbert_options_t::numthreads, skylark::ml::model_t< InputType, OutputType >::predict(), read(), skylark::ml::model_t< InputType, OutputType >::save(), ShiftForLogistic(), hilbert_options_t::testfile, BlockADMMSolver< T >::train(), and hilbert_options_t::trainfile.
Referenced by hilbert_options_t::hilbert_options_t().
void ShiftForLogistic (LocalMatrixType & Y)
Definition at line 144 of file run.hpp.
Referenced by run().