Skylark (Sketching Library): skylark::sketch::CT_data_t Struct Reference
skylark::sketch::CT_data_t Struct Reference
#include <CT_data.hpp>
Classes
struct params_t
Params structure.
Public Types
typedef dense_transform_data_t
< bstrand::cauchy_distribution > base_t
Public Member Functions
CT_data_t (int N, int S, double C, skylark::base::context_t &context)
CT_data_t (int N, int S, const params_t &params, skylark::base::context_t &context)
CT_data_t (const boost::property_tree::ptree &pt)
virtual boost::property_tree::ptree to_ptree () const
Protected Member Functions
CT_data_t (int N, int S, double C, const skylark::base::context_t &context, std::string type)
Detailed Description
Cauchy Transform (data)
The CT is simply a dense random matrix with i.i.d Cauchy variables
Definition at line 20 of file CT_data.hpp.
Member Typedef Documentation
typedef dense_transform_data_t<bstrand::cauchy_distribution> skylark::sketch::CT_data_t::base_t
Reimplemented from skylark::sketch::dense_transform_data_t< bstrand::cauchy_distribution >.
Definition at line 23 of file CT_data.hpp.
Constructor & Destructor Documentation
skylark::sketch::CT_data_t::CT_data_t (int N, int S, double C, skylark::base::context_t & context) [inline]
Definition at line 35 of file CT_data.hpp.
References skylark::sketch::dense_transform_data_t< bstrand::cauchy_distribution >::build().
skylark::sketch::CT_data_t::CT_data_t (int N, int S, const params_t & params, skylark::base::context_t & context) [inline]
Definition at line 41 of file CT_data.hpp.
References skylark::sketch::dense_transform_data_t< bstrand::cauchy_distribution >::build().
skylark::sketch::CT_data_t::CT_data_t (const boost::property_tree::ptree & pt) [inline]
Definition at line 49 of file CT_data.hpp.
References skylark::sketch::dense_transform_data_t< bstrand::cauchy_distribution >::build().
skylark::sketch::CT_data_t::CT_data_t (int N, int S, double C, const skylark::base::context_t & context, std::string type) [inline, protected]
Definition at line 73 of file CT_data.hpp.
Member Function Documentation
virtual boost::property_tree::ptree skylark::sketch::CT_data_t::to_ptree () const [inline, virtual]
Serializes a sketch to a string.
Parameters:
[out] property_tree describing the sketch.
Reimplemented from skylark::sketch::dense_transform_data_t< bstrand::cauchy_distribution >.
Definition at line 64 of file CT_data.hpp.
References skylark::sketch::sketch_transform_data_t::add_common().
The documentation for this struct was generated from the following file:
/var/lib/jenkins/jobs/Skylark/workspace/sketch/CT_data.hpp