Skylark (Sketching Library): skylark::algorithms::accelerated_regression_solver_t< regression_problem_t< elem::DistMatrix< ValueType, VD, elem::STAR >, linear_tag, l2_tag, no_reg_tag >, elem::DistMatrix< ValueType, VD, elem::STAR >, elem::DistMatrix< ValueType, elem::STAR, elem::STAR >, blendenpik_tag< PrecondTag > > Class Template Reference
skylark::algorithms::accelerated_regression_solver_t< regression_problem_t< elem::DistMatrix< ValueType, VD, elem::STAR >, linear_tag, l2_tag, no_reg_tag >, elem::DistMatrix< ValueType, VD, elem::STAR >, elem::DistMatrix< ValueType, elem::STAR, elem::STAR >, blendenpik_tag< PrecondTag > > Class Template Reference
Specialization for Blendenpik algorithm.
#include <accelerated_linearl2_regression_solver_Elemental.hpp>
Public Types
typedef ValueType value_type
typedef elem::DistMatrix
< ValueType, VD, elem::STAR > matrix_type
typedef elem::DistMatrix
< ValueType, VD, elem::STAR > rhs_type
typedef elem::DistMatrix
< ValueType, elem::STAR,
elem::STAR > sol_type
typedef regression_problem_t
< matrix_type, linear_tag,
l2_tag, no_reg_tag > problem_type
Public Member Functions
accelerated_regression_solver_t (const problem_type &problem, base::context_t &context)
~accelerated_regression_solver_t ()
int solve (const rhs_type &b, sol_type &x)
Detailed Description
template<typename ValueType, elem::Distribution VD, typename PrecondTag>
class skylark::algorithms::accelerated_regression_solver_t< regression_problem_t< elem::DistMatrix< ValueType, VD, elem::STAR >, linear_tag, l2_tag, no_reg_tag >, elem::DistMatrix< ValueType, VD, elem::STAR >, elem::DistMatrix< ValueType, elem::STAR, elem::STAR >, blendenpik_tag< PrecondTag > >
Specialization for Blendenpik algorithm.
Definition at line 149 of file accelerated_linearl2_regression_solver_Elemental.hpp.
Member Typedef Documentation
template<typename ValueType , elem::Distribution VD, typename PrecondTag > typedef elem::DistMatrix<ValueType, VD, elem::STAR> skylark::algorithms::accelerated_regression_solver_t< regression_problem_t< elem::DistMatrix< ValueType, VD, elem::STAR >, linear_tag, l2_tag, no_reg_tag >, elem::DistMatrix< ValueType, VD, elem::STAR >, elem::DistMatrix< ValueType, elem::STAR, elem::STAR >, blendenpik_tag< PrecondTag > >::matrix_type
Definition at line 160 of file accelerated_linearl2_regression_solver_Elemental.hpp.
template<typename ValueType , elem::Distribution VD, typename PrecondTag > typedef regression_problem_t<matrix_type, linear_tag, l2_tag, no_reg_tag> skylark::algorithms::accelerated_regression_solver_t< regression_problem_t< elem::DistMatrix< ValueType, VD, elem::STAR >, linear_tag, l2_tag, no_reg_tag >, elem::DistMatrix< ValueType, VD, elem::STAR >, elem::DistMatrix< ValueType, elem::STAR, elem::STAR >, blendenpik_tag< PrecondTag > >::problem_type
Definition at line 165 of file accelerated_linearl2_regression_solver_Elemental.hpp.
template<typename ValueType , elem::Distribution VD, typename PrecondTag > typedef elem::DistMatrix<ValueType, VD, elem::STAR> skylark::algorithms::accelerated_regression_solver_t< regression_problem_t< elem::DistMatrix< ValueType, VD, elem::STAR >, linear_tag, l2_tag, no_reg_tag >, elem::DistMatrix< ValueType, VD, elem::STAR >, elem::DistMatrix< ValueType, elem::STAR, elem::STAR >, blendenpik_tag< PrecondTag > >::rhs_type
Definition at line 161 of file accelerated_linearl2_regression_solver_Elemental.hpp.
template<typename ValueType , elem::Distribution VD, typename PrecondTag > typedef elem::DistMatrix<ValueType, elem::STAR, elem::STAR> skylark::algorithms::accelerated_regression_solver_t< regression_problem_t< elem::DistMatrix< ValueType, VD, elem::STAR >, linear_tag, l2_tag, no_reg_tag >, elem::DistMatrix< ValueType, VD, elem::STAR >, elem::DistMatrix< ValueType, elem::STAR, elem::STAR >, blendenpik_tag< PrecondTag > >::sol_type
Definition at line 162 of file accelerated_linearl2_regression_solver_Elemental.hpp.
template<typename ValueType , elem::Distribution VD, typename PrecondTag > typedef ValueType skylark::algorithms::accelerated_regression_solver_t< regression_problem_t< elem::DistMatrix< ValueType, VD, elem::STAR >, linear_tag, l2_tag, no_reg_tag >, elem::DistMatrix< ValueType, VD, elem::STAR >, elem::DistMatrix< ValueType, elem::STAR, elem::STAR >, blendenpik_tag< PrecondTag > >::value_type
Definition at line 158 of file accelerated_linearl2_regression_solver_Elemental.hpp.
Constructor & Destructor Documentation
template<typename ValueType , elem::Distribution VD, typename PrecondTag > skylark::algorithms::accelerated_regression_solver_t< regression_problem_t< elem::DistMatrix< ValueType, VD, elem::STAR >, linear_tag, l2_tag, no_reg_tag >, elem::DistMatrix< ValueType, VD, elem::STAR >, elem::DistMatrix< ValueType, elem::STAR, elem::STAR >, blendenpik_tag< PrecondTag > >::accelerated_regression_solver_t (const problem_type & problem, base::context_t & context) [inline]
Prepares the regressor to quickly solve given a right-hand side.
Parameters:
problem Problem to solve given right-hand side.
Definition at line 189 of file accelerated_linearl2_regression_solver_Elemental.hpp.
References skylark::algorithms::flinl2_internal::build_precond(), skylark::base::context_t::generate_random_samples_array(), and t.
template<typename ValueType , elem::Distribution VD, typename PrecondTag > skylark::algorithms::accelerated_regression_solver_t< regression_problem_t< elem::DistMatrix< ValueType, VD, elem::STAR >, linear_tag, l2_tag, no_reg_tag >, elem::DistMatrix< ValueType, VD, elem::STAR >, elem::DistMatrix< ValueType, elem::STAR, elem::STAR >, blendenpik_tag< PrecondTag > >::~accelerated_regression_solver_t () [inline]
Definition at line 237 of file accelerated_linearl2_regression_solver_Elemental.hpp.
Member Function Documentation
template<typename ValueType , elem::Distribution VD, typename PrecondTag > int skylark::algorithms::accelerated_regression_solver_t< regression_problem_t< elem::DistMatrix< ValueType, VD, elem::STAR >, linear_tag, l2_tag, no_reg_tag >, elem::DistMatrix< ValueType, VD, elem::STAR >, elem::DistMatrix< ValueType, elem::STAR, elem::STAR >, blendenpik_tag< PrecondTag > >::solve (const rhs_type & b, sol_type & x) [inline]
Definition at line 244 of file accelerated_linearl2_regression_solver_Elemental.hpp.
References skylark::nla::LSQR().
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/Skylark/workspace/algorithms/regression/accelerated_linearl2_regression_solver_Elemental.hpp