Skylark (Sketching Library): skylark::sketch::LaplacianRFT_data_t Struct Reference
skylark::sketch::LaplacianRFT_data_t Struct Reference
#include <RFT_data.hpp>
Classes
struct params_t
Params structure.
Public Types
typedef RFT_data_t
< bstrand::cauchy_distribution > base_t
Public Member Functions
LaplacianRFT_data_t (int N, int S, double sigma, base::context_t &context)
LaplacianRFT_data_t (int N, int S, const params_t &params, base::context_t &context)
LaplacianRFT_data_t (const boost::property_tree::ptree &pt)
virtual boost::property_tree::ptree to_ptree () const
Protected Member Functions
LaplacianRFT_data_t (int N, int S, double sigma, const base::context_t &context, std::string type)
Detailed Description
Definition at line 145 of file RFT_data.hpp.
Member Typedef Documentation
typedef RFT_data_t<bstrand::cauchy_distribution > skylark::sketch::LaplacianRFT_data_t::base_t
Reimplemented from skylark::sketch::RFT_data_t< bstrand::cauchy_distribution >.
Definition at line 148 of file RFT_data.hpp.
Constructor & Destructor Documentation
skylark::sketch::LaplacianRFT_data_t::LaplacianRFT_data_t (int N, int S, double sigma, base::context_t & context) [inline]
Definition at line 160 of file RFT_data.hpp.
References skylark::sketch::RFT_data_t< bstrand::cauchy_distribution >::build().
skylark::sketch::LaplacianRFT_data_t::LaplacianRFT_data_t (int N, int S, const params_t & params, base::context_t & context) [inline]
Definition at line 168 of file RFT_data.hpp.
References skylark::sketch::RFT_data_t< bstrand::cauchy_distribution >::build().
skylark::sketch::LaplacianRFT_data_t::LaplacianRFT_data_t (const boost::property_tree::ptree & pt) [inline]
Definition at line 176 of file RFT_data.hpp.
References skylark::sketch::RFT_data_t< bstrand::cauchy_distribution >::build().
skylark::sketch::LaplacianRFT_data_t::LaplacianRFT_data_t (int N, int S, double sigma, const base::context_t & context, std::string type) [inline, protected]
Definition at line 201 of file RFT_data.hpp.
Member Function Documentation
virtual boost::property_tree::ptree skylark::sketch::LaplacianRFT_data_t::to_ptree () const [inline, virtual]
Serializes a sketch to a string.
Parameters:
[out] property_tree describing the sketch.
Reimplemented from skylark::sketch::RFT_data_t< bstrand::cauchy_distribution >.
Definition at line 192 of file RFT_data.hpp.
References skylark::sketch::sketch_transform_data_t::add_common().
The documentation for this struct was generated from the following file:
/var/lib/jenkins/jobs/Skylark/workspace/sketch/RFT_data.hpp