Skylark (Sketching Library): /var/lib/jenkins/jobs/Skylark/workspace/python-skylark/skylark/ml/admm/cproxoperators/libproxoperators.h File Reference
/var/lib/jenkins/jobs/Skylark/workspace/python-skylark/skylark/ml/admm/cproxoperators/libproxoperators.h File Reference
Functions
int logexp (int index, double *v, int n, double lambda, double *x, int MAXITER, double epsilon, int DISPLAY)
double logsumexp (double *x, int n)
double objective (int index, double *x, double *v, int n, double lambda)
double normsquare (double *x, double *y, int n)
Function Documentation
int logexp (int index, double * v, int n, double lambda, double * x, int MAXITER, double epsilon, int DISPLAY)
Definition at line 191 of file libproxoperators.c.
References logsumexp(), n, objective(), and t.
double logsumexp (double * x, int n)
Definition at line 266 of file libproxoperators.c.
References max(), and n.
Referenced by logexp(), and objective().
double normsquare (double * x, double * y, int n)
Definition at line 258 of file libproxoperators.c.
References n.
Referenced by objective().
double objective (int index, double * x, double * v, int n, double lambda)
Definition at line 252 of file libproxoperators.c.
References logsumexp(), and normsquare().
Referenced by logexp().