Skylark (Sketching Library): /var/lib/jenkins/jobs/Skylark/workspace/tests/unit/MixedGemmTest.cpp File Reference
/var/lib/jenkins/jobs/Skylark/workspace/tests/unit/MixedGemmTest.cpp File Reference
#include <vector>
#include <boost/mpi.hpp>
#include <boost/test/minimal.hpp>
#include <elemental.hpp>
#include <CombBLAS.h>
#include <SpParMat.h>
#include <skylark.hpp>
#include "../../base/Gemm.hpp"
#include "../../base/Gemm_detail.hpp"
Typedefs
typedef elem::Matrix< double > MatrixType
typedef elem::DistMatrix
< double, elem::VC, elem::STAR > DistMatrixVCSType
typedef elem::DistMatrix< double > DistMatrixType
typedef SpDCCols< size_t, double > col_t
typedef SpParMat< size_t,
double, col_t > cbDistMatrixType
Functions
template<typename dist_matrix_t >
void check_matrix (const dist_matrix_t &result, const MatrixType &expected, const std::string error)
int test_main (int argc, char *argv[])
Typedef Documentation
typedef SpParMat< size_t, double, col_t > cbDistMatrixType
Definition at line 21 of file MixedGemmTest.cpp.
typedef SpDCCols< size_t, double> col_t
Definition at line 20 of file MixedGemmTest.cpp.
typedef elem::DistMatrix<double> DistMatrixType
Definition at line 18 of file MixedGemmTest.cpp.
typedef elem::DistMatrix<double, elem::VC, elem::STAR> DistMatrixVCSType
Definition at line 17 of file MixedGemmTest.cpp.
typedef elem::Matrix<double> MatrixType
Typedef DistMatrix and Matrix
Definition at line 16 of file MixedGemmTest.cpp.
Function Documentation
template<typename dist_matrix_t > void check_matrix (const dist_matrix_t & result, const MatrixType & expected, const std::string error)
Definition at line 31 of file MixedGemmTest.cpp.
Referenced by test_main().
int test_main (int argc, char * argv[])
Definition at line 48 of file MixedGemmTest.cpp.
References check_matrix(), and skylark::base::Gemm().