Skylark (Sketching Library): skylark::base Namespace Reference
skylark::base Namespace Reference
Namespaces
namespace detail
namespace qr
Classes
struct computed_matrix_t
struct context_t
struct skylark_exception
define a base exception
struct elemental_exception
exceptions thrown by Elemental
struct combblas_exception
exceptions thrown by CombBLAS
struct mpi_exception
exceptions thrown by Boost MPI
struct sketch_exception
exceptions in the sketch layer
struct nla_exception
exceptions in the nla layer
struct random123_exception
exceptions in the Random123 layer
struct io_exception
exceptions when doing I/O
struct allocation_exception
exceptions for allocating memory in sketch layer
struct unsupported_matrix_distribution
exceptions for unsupported matrix distributions in Elemental
struct unsupported_base_operation
exceptions for unsupported base operation
struct sparse_matrix_t
Typedefs
typedef boost::error_info
< struct tag_error_code, int > error_code
predefined structure for error code
typedef boost::error_info
< struct tag_error_msg,
std::string > error_msg
predefined structure for error msg
typedef boost::error_info
< struct tag_stack_trace,
std::string > stack_trace
predefined structure for trace error (appends messages)
typedef boost::error_info
< struct tag_append_trace,
std::string > append_trace
Functions
boost::property_tree::ptree & operator<< (boost::property_tree::ptree &sk, const context_t &data)
template<typename CT , typename RT , typename OT >
void Gemm (elem::Orientation oA, elem::Orientation oB, typename utility::typer_t< OT >::value_type alpha, const computed_matrix_t< CT > &A, const RT &B, typename utility::typer_t< OT >::value_type beta, OT &C)
template<typename CT , typename RT , typename OT >
void Gemm (elem::Orientation oA, elem::Orientation oB, typename utility::typer_t< OT >::value_type alpha, const computed_matrix_t< CT > &A, const RT &B, OT &C)
template<typename CT , typename RT , typename OT >
void Gemm (elem::Orientation oA, elem::Orientation oB, typename utility::typer_t< OT >::value_type alpha, const RT &A, const computed_matrix_t< CT > &B, typename utility::typer_t< OT >::value_type beta, OT &C)
template<typename CT , typename RT , typename OT >
void Gemm (elem::Orientation oA, elem::Orientation oB, typename utility::typer_t< OT >::value_type alpha, const RT &A, const computed_matrix_t< CT > &B, OT &C)
template<typename CT1 , typename CT2 , typename OT >
void Gemm (elem::Orientation oA, elem::Orientation oB, typename utility::typer_t< OT >::value_type alpha, const computed_matrix_t< CT1 > &A, const computed_matrix_t< CT2 > &B, typename utility::typer_t< OT >::value_type beta, OT &C)
template<typename CT1 , typename CT2 , typename OT >
void Gemm (elem::Orientation oA, elem::Orientation oB, typename utility::typer_t< OT >::value_type alpha, const computed_matrix_t< CT1 > &A, const computed_matrix_t< CT2 > &B, OT &C)
template<typename T >
int Height (const sparse_matrix_t< T > &A)
template<typename T >
int Width (const sparse_matrix_t< T > &A)
template<typename T >
void Transpose (const sparse_matrix_t< T > &A, sparse_matrix_t< T > &B)
template<typename T >
void ColumnView (sparse_matrix_t< T > &A, sparse_matrix_t< T > &B, int j, int width)
template<typename T >
sparse_matrix_t< T > ColumnView (const sparse_matrix_t< T > &B, int j, int width)
Typedef Documentation
typedef boost::error_info<struct tag_append_trace, std::string> skylark::base::append_trace
Definition at line 71 of file exception.hpp.
typedef boost::error_info<struct tag_error_code, int> skylark::base::error_code
predefined structure for error code
Definition at line 65 of file exception.hpp.
typedef boost::error_info<struct tag_error_msg, std::string> skylark::base::error_msg
predefined structure for error msg
Definition at line 67 of file exception.hpp.
typedef boost::error_info<struct tag_stack_trace, std::string> skylark::base::stack_trace
predefined structure for trace error (appends messages)
Definition at line 70 of file exception.hpp.
Function Documentation
template<typename T > void skylark::base::ColumnView (sparse_matrix_t< T > & A, sparse_matrix_t< T > & B, int j, int width) [inline]
Definition at line 26 of file viewing.hpp.
References skylark::base::sparse_matrix_t< ValueType >::attach(), skylark::base::sparse_matrix_t< ValueType >::height(), skylark::base::sparse_matrix_t< ValueType >::indices(), skylark::base::sparse_matrix_t< ValueType >::indptr(), and skylark::base::sparse_matrix_t< ValueType >::values().
Referenced by ColumnView().
template<typename T > sparse_matrix_t<T> skylark::base::ColumnView (const sparse_matrix_t< T > & B, int j, int width) [inline]
Definition at line 44 of file viewing.hpp.
References ColumnView().
template<typename CT , typename RT , typename OT > void skylark::base::Gemm (elem::Orientation oA, elem::Orientation oB, typename utility::typer_t< OT >::value_type alpha, const computed_matrix_t< CT > & A, const RT & B, typename utility::typer_t< OT >::value_type beta, OT & C) [inline]
Definition at line 488 of file Gemm.hpp.
References skylark::base::computed_matrix_t< MatrixType >::materialize().
Referenced by skylark::nla::mat_precond_t< XType, NType >::apply(), skylark::nla::mat_precond_t< XType, NType >::apply_adjoint(), skylark::nla::ChebyshevLS(), Gemm(), skylark::nla::LSQR(), main(), skylark::nla::randsvd_t< SketchTransform >::operator()(), skylark::ml::model_t< InputType, OutputType >::predict(), skylark::algorithms::regression_solver_t< regression_problem_t< elem::DistMatrix< ValueType, VD, elem::STAR >, linear_tag, l2_tag, no_reg_tag >, elem::DistMatrix< ValueType, VD, elem::STAR >, elem::DistMatrix< ValueType, elem::STAR, elem::STAR >, qr_l2_solver_tag >::solve(), skylark::algorithms::regression_solver_t< regression_problem_t< elem::DistMatrix< ValueType, VD, elem::STAR >, linear_tag, l2_tag, no_reg_tag >, elem::DistMatrix< ValueType, VD, elem::STAR >, elem::DistMatrix< ValueType, elem::STAR, elem::STAR >, svd_l2_solver_tag >::solve(), skylark::algorithms::regression_solver_t< regression_problem_t< elem::DistMatrix< ValueType, VD, elem::STAR >, linear_tag, l2_tag, no_reg_tag >, elem::DistMatrix< ValueType, VD, elem::STAR >, elem::DistMatrix< ValueType, elem::STAR, elem::STAR >, sne_l2_solver_tag >::solve(), skylark::algorithms::regression_solver_t< regression_problem_t< base::computed_matrix_t< elem::DistMatrix< ValueType, VD, elem::STAR > >, linear_tag, l2_tag, no_reg_tag >, elem::DistMatrix< ValueType, VD, elem::STAR >, elem::DistMatrix< ValueType, elem::STAR, elem::STAR >, sne_l2_solver_tag >::solve(), test_main(), and BlockADMMSolver< T >::train().
template<typename CT , typename RT , typename OT > void skylark::base::Gemm (elem::Orientation oA, elem::Orientation oB, typename utility::typer_t< OT >::value_type alpha, const computed_matrix_t< CT > & A, const RT & B, OT & C) [inline]
Definition at line 495 of file Gemm.hpp.
References Gemm(), and skylark::base::computed_matrix_t< MatrixType >::materialize().
template<typename CT , typename RT , typename OT > void skylark::base::Gemm (elem::Orientation oA, elem::Orientation oB, typename utility::typer_t< OT >::value_type alpha, const RT & A, const computed_matrix_t< CT > & B, typename utility::typer_t< OT >::value_type beta, OT & C) [inline]
Definition at line 502 of file Gemm.hpp.
References Gemm(), and skylark::base::computed_matrix_t< MatrixType >::materialize().
template<typename CT , typename RT , typename OT > void skylark::base::Gemm (elem::Orientation oA, elem::Orientation oB, typename utility::typer_t< OT >::value_type alpha, const RT & A, const computed_matrix_t< CT > & B, OT & C) [inline]
Definition at line 510 of file Gemm.hpp.
References Gemm(), and skylark::base::computed_matrix_t< MatrixType >::materialize().
template<typename CT1 , typename CT2 , typename OT > void skylark::base::Gemm (elem::Orientation oA, elem::Orientation oB, typename utility::typer_t< OT >::value_type alpha, const computed_matrix_t< CT1 > & A, const computed_matrix_t< CT2 > & B, typename utility::typer_t< OT >::value_type beta, OT & C) [inline]
Definition at line 517 of file Gemm.hpp.
References Gemm(), and skylark::base::computed_matrix_t< MatrixType >::materialize().
template<typename CT1 , typename CT2 , typename OT > void skylark::base::Gemm (elem::Orientation oA, elem::Orientation oB, typename utility::typer_t< OT >::value_type alpha, const computed_matrix_t< CT1 > & A, const computed_matrix_t< CT2 > & B, OT & C) [inline]
Definition at line 525 of file Gemm.hpp.
References Gemm(), and skylark::base::computed_matrix_t< MatrixType >::materialize().
template<typename T > int skylark::base::Height (const sparse_matrix_t< T > & A)
Definition at line 9 of file query.hpp.
References skylark::base::sparse_matrix_t< ValueType >::height().
Referenced by skylark::nla::ApproximateLeastSquares(), skylark::nla::ChebyshevLS(), skylark::nla::FastLeastSquares(), skylark::nla::LSQR(), skylark::ml::model_t< InputType, OutputType >::predict(), run(), skylark::algorithms::regression_solver_t< regression_problem_t< MatrixType, linear_tag, l2_tag, no_reg_tag >, RhsType, SolType, iterative_l2_solver_tag< KrylovMethod > >::solve(), and BlockADMMSolver< T >::train().
boost::property_tree::ptree& skylark::base::operator<< (boost::property_tree::ptree & sk, const context_t & data)
Serializes the context to a JSON structure.
Parameters:
[out] JSON encoded state of the context.
Definition at line 176 of file context.hpp.
template<typename T > void skylark::base::Transpose (const sparse_matrix_t< T > & A, sparse_matrix_t< T > & B)
Definition at line 252 of file sparse_matrix.hpp.
References skylark::base::sparse_matrix_t< ValueType >::attach(), skylark::base::sparse_matrix_t< ValueType >::height(), skylark::base::sparse_matrix_t< ValueType >::indices(), skylark::base::sparse_matrix_t< ValueType >::indptr(), skylark::base::sparse_matrix_t< ValueType >::locked_values(), m, n, skylark::base::sparse_matrix_t< ValueType >::nonzeros(), and skylark::base::sparse_matrix_t< ValueType >::width().
Referenced by test_main().
template<typename T > int skylark::base::Width (const sparse_matrix_t< T > & A)
Definition at line 14 of file query.hpp.
References skylark::base::sparse_matrix_t< ValueType >::width().
Referenced by skylark::nla::ApproximateLeastSquares(), skylark::nla::ChebyshevLS(), skylark::nla::FastLeastSquares(), skylark::nla::LSQR(), skylark::ml::model_t< InputType, OutputType >::predict(), skylark::algorithms::regression_solver_t< regression_problem_t< MatrixType, linear_tag, l2_tag, no_reg_tag >, RhsType, SolType, iterative_l2_solver_tag< KrylovMethod > >::solve(), and BlockADMMSolver< T >::train().