Skylark (Sketching Library): skylark::sketch::hash_transform_t< InputMatrixType, OutputMatrixType, IdxDistributionType, ValueDistribution > Struct Template Reference
skylark::sketch::hash_transform_t< InputMatrixType, OutputMatrixType, IdxDistributionType, ValueDistribution > Struct Template Reference
#include <hash_transform.hpp>
Public Types
typedef InputMatrixType matrix_type
typedef OutputMatrixType output_matrix_type
typedef hash_transform_data_t
< IdxDistributionType,
ValueDistribution > data_type
Public Member Functions
hash_transform_t (int N, int S, base::context_t &context)
hash_transform_t (const data_type &other_data)
hash_transform_t (const boost::property_tree::ptree &pt)
void apply (const matrix_type &A, output_matrix_type &sketch_of_A, columnwise_tag dimension) const
void apply (const matrix_type &A, output_matrix_type &sketch_of_A, rowwise_tag dimension) const
Detailed Description
template<typename InputMatrixType, typename OutputMatrixType, template< typename > class IdxDistributionType, template< typename > class ValueDistribution>
struct skylark::sketch::hash_transform_t< InputMatrixType, OutputMatrixType, IdxDistributionType, ValueDistribution >
Definition at line 22 of file hash_transform.hpp.
Member Typedef Documentation
template<typename InputMatrixType, typename OutputMatrixType, template< typename > class IdxDistributionType, template< typename > class ValueDistribution> typedef hash_transform_data_t<IdxDistributionType, ValueDistribution> skylark::sketch::hash_transform_t< InputMatrixType, OutputMatrixType, IdxDistributionType, ValueDistribution >::data_type
Definition at line 29 of file hash_transform.hpp.
template<typename InputMatrixType, typename OutputMatrixType, template< typename > class IdxDistributionType, template< typename > class ValueDistribution> typedef InputMatrixType skylark::sketch::hash_transform_t< InputMatrixType, OutputMatrixType, IdxDistributionType, ValueDistribution >::matrix_type
Definition at line 26 of file hash_transform.hpp.
template<typename InputMatrixType, typename OutputMatrixType, template< typename > class IdxDistributionType, template< typename > class ValueDistribution> typedef OutputMatrixType skylark::sketch::hash_transform_t< InputMatrixType, OutputMatrixType, IdxDistributionType, ValueDistribution >::output_matrix_type
Definition at line 27 of file hash_transform.hpp.
Constructor & Destructor Documentation
template<typename InputMatrixType, typename OutputMatrixType, template< typename > class IdxDistributionType, template< typename > class ValueDistribution> skylark::sketch::hash_transform_t< InputMatrixType, OutputMatrixType, IdxDistributionType, ValueDistribution >::hash_transform_t (int N, int S, base::context_t & context) [inline]
Definition at line 31 of file hash_transform.hpp.
template<typename InputMatrixType, typename OutputMatrixType, template< typename > class IdxDistributionType, template< typename > class ValueDistribution> skylark::sketch::hash_transform_t< InputMatrixType, OutputMatrixType, IdxDistributionType, ValueDistribution >::hash_transform_t (const data_type & other_data) [inline]
Definition at line 39 of file hash_transform.hpp.
template<typename InputMatrixType, typename OutputMatrixType, template< typename > class IdxDistributionType, template< typename > class ValueDistribution> skylark::sketch::hash_transform_t< InputMatrixType, OutputMatrixType, IdxDistributionType, ValueDistribution >::hash_transform_t (const boost::property_tree::ptree & pt) [inline]
Definition at line 47 of file hash_transform.hpp.
Member Function Documentation
template<typename InputMatrixType, typename OutputMatrixType, template< typename > class IdxDistributionType, template< typename > class ValueDistribution> void skylark::sketch::hash_transform_t< InputMatrixType, OutputMatrixType, IdxDistributionType, ValueDistribution >::apply (const matrix_type & A, output_matrix_type & sketch_of_A, columnwise_tag dimension) const [inline]
Definition at line 55 of file hash_transform.hpp.
Referenced by skylark::sketch::CWT_t< InputMatrixType, OutputMatrixType >::apply(), skylark::sketch::MMT_t< InputMatrixType, OutputMatrixType >::apply(), and skylark::sketch::WZT_t< InputMatrixType, OutputMatrixType >::apply().
template<typename InputMatrixType, typename OutputMatrixType, template< typename > class IdxDistributionType, template< typename > class ValueDistribution> void skylark::sketch::hash_transform_t< InputMatrixType, OutputMatrixType, IdxDistributionType, ValueDistribution >::apply (const matrix_type & A, output_matrix_type & sketch_of_A, rowwise_tag dimension) const [inline]
Definition at line 64 of file hash_transform.hpp.
The documentation for this struct was generated from the following file:
/var/lib/jenkins/jobs/Skylark/workspace/sketch/hash_transform.hpp