package:
  name: metis
  version: "5.1.0"

source:
  fn: metis-5.1.0.tar.gz
  url: http://glaros.dtc.umn.edu/gkhome/fetch/sw/metis/metis-5.1.0.tar.gz
  md5: 5465e67079419a69e0116de24fce58fe


requirements:
  build:
    - gcc
    - cmake

  run:
    - libgcc	

about:
  home: http://glaros.dtc.umn.edu/gkhome/metis/metis/overview
  license_file: LICENSE.txt
  summary: 'Serial programs for partitioning graphs, partitioning finite element meshes, and producing fill reducing orderings for sparse matrices'

