Skylark (Sketching Library): /var/lib/jenkins/jobs/Skylark/workspace/ml/utils.hpp File Reference
/var/lib/jenkins/jobs/Skylark/workspace/ml/utils.hpp File Reference
#include <elemental.hpp>
Functions
int max (elem::Matrix< double > Y)
int min (elem::Matrix< double > Y)
template<class LabelType >
int GetNumTargets (const boost::mpi::communicator &comm, LabelType &Y)
Function Documentation
template<class LabelType > int GetNumTargets (const boost::mpi::communicator & comm, LabelType & Y)
Definition at line 17 of file utils.hpp.
References max(), and min().
Referenced by BlockADMMSolver< T >::train().
int max (elem::Matrix< double > Y)
Definition at line 6 of file utils.hpp.
Referenced by GetNumTargets(), logsumexp(), skylark::nla::LSQR(), skylark::ml::model_t< InputType, OutputType >::model_t(), skylark::utility::random_array_t::random_array_t(), skylark::utility::random_samples_array_t< value_distribution_type >::random_samples_array_t(), read_libsvm(), and skylark::base::sparse_matrix_t< ValueType >::set().
int min (elem::Matrix< double > Y)
Definition at line 11 of file utils.hpp.
Referenced by BlockADMMSolver< T >::BlockADMMSolver(), GetNumTargets(), skylark::nla::LSQR(), and skylark::nla::randsvd_t< SketchTransform >::operator()().