Skylark (Sketching Library): skylark::sketch::MMT_data_t Struct Reference
skylark::sketch::MMT_data_t Struct Reference
#include <MMT_data.hpp>
Classes
struct params_t
Params structure.
Public Types
typedef hash_transform_data_t
< boost::random::uniform_int_distribution,
boost::random::cauchy_distribution > base_t
Public Member Functions
MMT_data_t (int N, int S, base::context_t &context)
MMT_data_t (int N, int S, const params_t &params, base::context_t &context)
MMT_data_t (const boost::property_tree::ptree &pt)
virtual boost::property_tree::ptree to_ptree () const
Protected Member Functions
MMT_data_t (int N, int S, const base::context_t &context, std::string type)
Detailed Description
Meng-Mahoney Transform (data)
Meng-Mahoney Transform is very similar to the Clarkson-Woodruff Transform: it replaces the +1/-1 diagonal with Cauchy random enteries. Thus, it provides a low-distortion of l1-norm subspace embedding.
See Meng and Mahoney's STOC'13 paper.
Definition at line 21 of file MMT_data.hpp.
Member Typedef Documentation
typedef hash_transform_data_t< boost::random::uniform_int_distribution, boost::random::cauchy_distribution > skylark::sketch::MMT_data_t::base_t
Reimplemented from skylark::sketch::hash_transform_data_t< boost::random::uniform_int_distribution, boost::random::cauchy_distribution >.
Definition at line 27 of file MMT_data.hpp.
Constructor & Destructor Documentation
skylark::sketch::MMT_data_t::MMT_data_t (int N, int S, base::context_t & context) [inline]
Definition at line 34 of file MMT_data.hpp.
References skylark::sketch::hash_transform_data_t< boost::random::uniform_int_distribution, boost::random::cauchy_distribution >::build().
skylark::sketch::MMT_data_t::MMT_data_t (int N, int S, const params_t & params, base::context_t & context) [inline]
Definition at line 40 of file MMT_data.hpp.
References skylark::sketch::hash_transform_data_t< boost::random::uniform_int_distribution, boost::random::cauchy_distribution >::build().
skylark::sketch::MMT_data_t::MMT_data_t (const boost::property_tree::ptree & pt) [inline]
Definition at line 46 of file MMT_data.hpp.
References skylark::sketch::hash_transform_data_t< boost::random::uniform_int_distribution, boost::random::cauchy_distribution >::build().
skylark::sketch::MMT_data_t::MMT_data_t (int N, int S, const base::context_t & context, std::string type) [inline, protected]
Definition at line 66 of file MMT_data.hpp.
Member Function Documentation
virtual boost::property_tree::ptree skylark::sketch::MMT_data_t::to_ptree () const [inline, virtual]
Serializes a sketch to a string.
Parameters:
[out] property_tree describing the sketch.
Reimplemented from skylark::sketch::hash_transform_data_t< boost::random::uniform_int_distribution, boost::random::cauchy_distribution >.
Definition at line 58 of file MMT_data.hpp.
References skylark::sketch::sketch_transform_data_t::add_common().
The documentation for this struct was generated from the following file:
/var/lib/jenkins/jobs/Skylark/workspace/sketch/MMT_data.hpp