Skylark (Sketching Library): skylark::sketch::JLT_data_t Struct Reference
skylark::sketch::JLT_data_t Struct Reference
#include <JLT_data.hpp>
Classes
struct params_t
Params structure.
Public Types
typedef dense_transform_data_t
< bstrand::normal_distribution > base_t
Public Member Functions
JLT_data_t (int N, int S, skylark::base::context_t &context)
JLT_data_t (int N, int S, const params_t &params, skylark::base::context_t &context)
JLT_data_t (const boost::property_tree::ptree &pt)
virtual boost::property_tree::ptree to_ptree () const
Protected Member Functions
JLT_data_t (int N, int S, const skylark::base::context_t &context, std::string type)
Detailed Description
Johnson-Lindenstrauss Transform (data).
The JLT is simply a dense random matrix with i.i.d normal entries.
Definition at line 17 of file JLT_data.hpp.
Member Typedef Documentation
typedef dense_transform_data_t<bstrand::normal_distribution> skylark::sketch::JLT_data_t::base_t
Reimplemented from skylark::sketch::dense_transform_data_t< bstrand::normal_distribution >.
Definition at line 20 of file JLT_data.hpp.
Constructor & Destructor Documentation
skylark::sketch::JLT_data_t::JLT_data_t (int N, int S, skylark::base::context_t & context) [inline]
Definition at line 27 of file JLT_data.hpp.
References skylark::sketch::dense_transform_data_t< bstrand::normal_distribution >::build().
skylark::sketch::JLT_data_t::JLT_data_t (int N, int S, const params_t & params, skylark::base::context_t & context) [inline]
Definition at line 33 of file JLT_data.hpp.
References skylark::sketch::dense_transform_data_t< bstrand::normal_distribution >::build().
skylark::sketch::JLT_data_t::JLT_data_t (const boost::property_tree::ptree & pt) [inline]
Definition at line 40 of file JLT_data.hpp.
References skylark::sketch::dense_transform_data_t< bstrand::normal_distribution >::build().
skylark::sketch::JLT_data_t::JLT_data_t (int N, int S, const skylark::base::context_t & context, std::string type) [inline, protected]
Definition at line 62 of file JLT_data.hpp.
Member Function Documentation
virtual boost::property_tree::ptree skylark::sketch::JLT_data_t::to_ptree () const [inline, virtual]
Serializes a sketch to a string.
Parameters:
[out] property_tree describing the sketch.
Reimplemented from skylark::sketch::dense_transform_data_t< bstrand::normal_distribution >.
Definition at line 54 of file JLT_data.hpp.
References skylark::sketch::sketch_transform_data_t::add_common().
The documentation for this struct was generated from the following file:
/var/lib/jenkins/jobs/Skylark/workspace/sketch/JLT_data.hpp