Skylark (Sketching Library): /var/lib/jenkins/jobs/Skylark/workspace/tests/unit/SparseSketchApplyCombBLASTest.cpp File Reference
/var/lib/jenkins/jobs/Skylark/workspace/tests/unit/SparseSketchApplyCombBLASTest.cpp File Reference
#include <vector>
#include <boost/mpi.hpp>
#include <boost/test/minimal.hpp>
#include "../../base/context.hpp"
#include "../../utility/distributions.hpp"
#include "../../sketch/hash_transform.hpp"
#include "../../base/sparse_matrix.hpp"
Classes
struct Dummy_t< InputMatrixType, OutputMatrixType >
Defines
#define SKYLARK_SKETCH_HPP 1
Typedefs
typedef FullyDistVec< size_t,
double > mpi_vector_t
typedef SpDCCols< size_t, double > col_t
typedef SpParMat< size_t,
double, col_t > DistMatrixType
typedef PlusTimesSRing< double,
double > PTDD
typedef
skylark::base::sparse_matrix_t
< double > LocalMatrixType
Functions
template<typename sketch_t >
void compute_sketch_matrix (sketch_t sketch, const DistMatrixType &A, DistMatrixType &result)
int test_main (int argc, char *argv[])
Define Documentation
#define SKYLARK_SKETCH_HPP 1
This test ensures that the sketch application (for CombBLAS matrices) is done correctly (on-the-fly matrix multiplication in the code is compared to true matrix multiplication). This test builds on the following assumptions:
CombBLAS PSpGEMM returns the correct result, and
the random numbers in row_idx and row_value (see hash_transform_data_t) are drawn from the promised distributions.
Definition at line 19 of file SparseSketchApplyCombBLASTest.cpp.
Typedef Documentation
typedef SpDCCols<size_t, double> col_t
Definition at line 28 of file SparseSketchApplyCombBLASTest.cpp.
typedef SpParMat<size_t, double, col_t> DistMatrixType
Definition at line 29 of file SparseSketchApplyCombBLASTest.cpp.
typedef skylark::base::sparse_matrix_t<double> LocalMatrixType
Definition at line 31 of file SparseSketchApplyCombBLASTest.cpp.
typedef FullyDistVec<size_t, double> mpi_vector_t
Definition at line 27 of file SparseSketchApplyCombBLASTest.cpp.
typedef PlusTimesSRing<double, double> PTDD
Definition at line 30 of file SparseSketchApplyCombBLASTest.cpp.
Function Documentation
template<typename sketch_t > void compute_sketch_matrix (sketch_t sketch, const DistMatrixType & A, DistMatrixType & result)
Definition at line 59 of file SparseSketchApplyCombBLASTest.cpp.
Referenced by test_main().
int test_main (int argc, char * argv[])
Definition at line 82 of file SparseSketchApplyCombBLASTest.cpp.
References skylark::sketch::hash_transform_t< InputMatrixType, OutputMatrixType, boost::random::uniform_int_distribution, skylark::utility::rademacher_distribution_t >::apply(), compute_sketch_matrix(), Dummy_t< InputMatrixType, OutputMatrixType >::getRowIdx(), Dummy_t< InputMatrixType, OutputMatrixType >::getRowValues(), m, and n.