Skylark (Sketching Library): skylark::sketch::ExpSemigroupRLT_data_t Struct Reference
skylark::sketch::ExpSemigroupRLT_data_t Struct Reference
#include <RLT_data.hpp>
Classes
struct params_t
Params structure.
Public Types
typedef RLT_data_t
< utility::standard_levy_distribution_t > base_t
Public Member Functions
ExpSemigroupRLT_data_t (int N, int S, double beta, skylark::base::context_t &context)
ExpSemigroupRLT_data_t (int N, int S, const params_t &params, skylark::base::context_t &context)
ExpSemigroupRLT_data_t (const boost::property_tree::ptree &pt)
virtual boost::property_tree::ptree to_ptree () const
Protected Member Functions
ExpSemigroupRLT_data_t (int N, int S, double beta, const skylark::base::context_t &context, std::string type)
Detailed Description
Random Features for Exponential Semigroup
Definition at line 81 of file RLT_data.hpp.
Member Typedef Documentation
typedef RLT_data_t<utility::standard_levy_distribution_t > skylark::sketch::ExpSemigroupRLT_data_t::base_t
Reimplemented from skylark::sketch::RLT_data_t< utility::standard_levy_distribution_t >.
Definition at line 84 of file RLT_data.hpp.
Constructor & Destructor Documentation
skylark::sketch::ExpSemigroupRLT_data_t::ExpSemigroupRLT_data_t (int N, int S, double beta, skylark::base::context_t & context) [inline]
Definition at line 96 of file RLT_data.hpp.
References skylark::sketch::RLT_data_t< utility::standard_levy_distribution_t >::build().
skylark::sketch::ExpSemigroupRLT_data_t::ExpSemigroupRLT_data_t (int N, int S, const params_t & params, skylark::base::context_t & context) [inline]
Definition at line 104 of file RLT_data.hpp.
References skylark::sketch::RLT_data_t< utility::standard_levy_distribution_t >::build().
skylark::sketch::ExpSemigroupRLT_data_t::ExpSemigroupRLT_data_t (const boost::property_tree::ptree & pt) [inline]
Definition at line 112 of file RLT_data.hpp.
References skylark::sketch::RLT_data_t< utility::standard_levy_distribution_t >::build().
skylark::sketch::ExpSemigroupRLT_data_t::ExpSemigroupRLT_data_t (int N, int S, double beta, const skylark::base::context_t & context, std::string type) [inline, protected]
Definition at line 136 of file RLT_data.hpp.
Member Function Documentation
virtual boost::property_tree::ptree skylark::sketch::ExpSemigroupRLT_data_t::to_ptree () const [inline, virtual]
Serializes a sketch to a string.
Parameters:
[out] property_tree describing the sketch.
Reimplemented from skylark::sketch::RLT_data_t< utility::standard_levy_distribution_t >.
Definition at line 128 of file RLT_data.hpp.
References skylark::sketch::sketch_transform_data_t::add_common().
The documentation for this struct was generated from the following file:
/var/lib/jenkins/jobs/Skylark/workspace/sketch/RLT_data.hpp