#!/bin/bash
set -e

mkdir -p $HOME/deps

if [ ! -d "deps/boost_1_55_0" ]; then
    pushd $HOME/deps
    wget http://sourceforge.net/projects/boost/files/boost/1.55.0/boost_1_55_0.tar.gz
    tar xvfz boost_1_55_0.tar.gz &> /dev/null
    cd boost_1_55_0
    ./bootstrap.sh --with-libraries=mpi,serialization,program_options,system,filesystem
    echo "using mpi ;" >> project-config.jam
    ./b2 link=static,shared &> /dev/null
    popd
fi

if [ ! -d "deps/Elemental" ]; then
    pushd $HOME/deps
    git clone https://github.com/elemental/Elemental.git Elemental
    if [ $? -ne 0 ]; then
        echo "Unable to clone Elemental"
        popd
        exit 1
    fi

    cd Elemental
    git checkout 71fce6e65c065e0b2f993435ca7524db7f54fa6f
    mkdir build
    cd build
    cmake -DEL_USE_64BIT_INTS=ON \
        -DEL_HAVE_QUADMATH=OFF -DCMAKE_BUILD_TYPE=Release -DEL_HYBRID=ON \
        -DBUILD_SHARED_LIBS=ON -DMATH_LIBS="-L/usr/lib -llapack -lopenblas -lm" \
        -DEL_DISABLE_SCALAPACK=ON -DEL_DISABLE_VALGRIND=ON \
        -DCMAKE_INSTALL_PREFIX=../install ../
    if [ $? -ne 0 ]; then
        echo "Unable to configure Elemental"
        popd
        exit 1
    fi

    make &> /dev/null
    if [ $? -ne 0 ]; then
        echo "Unable to compile Elemental"
        popd
        exit 1
    fi

    make install 1> /dev/null
    if [ $? -ne 0 ]; then
        echo "Unable to install Elemental under $HOME/deps/Elemental/install"
        popd
        exit 1
    fi
    popd
fi
