Skylark (Sketching Library): skylark::algorithms::flinl2_internal Namespace Reference
skylark::algorithms::flinl2_internal Namespace Reference
Functions
void BLAS() dtrcon (const char *norm, const char *uplo, const char *diag, const int *n, const double *A, const int *lda, double *rcond, double *work, int *iwork, int *info)
void BLAS() strcon (const char *norm, const char *uplo, const char *diag, const int *n, const float *A, const int *lda, float *rcond, float *work, int *iwork, int *info)
double utcondest (const elem::Matrix< double > &A)
double utcondest (const elem::Matrix< float > &A)
template<typename T >
double utcondest (const elem::DistMatrix< T, elem::STAR, elem::STAR > &A)
template<typename SolType , typename SketchType , typename PrecondType >
double build_precond (SketchType &SA, PrecondType &R, nla::precond_t< SolType > *&P, qr_precond_tag)
template<typename SolType , typename SketchType , typename PrecondType >
double build_precond (SketchType &SA, PrecondType &V, nla::precond_t< SolType > *&P, svd_precond_tag)
Function Documentation
template<typename SolType , typename SketchType , typename PrecondType > double skylark::algorithms::flinl2_internal::build_precond (SketchType & SA, PrecondType & R, nla::precond_t< SolType > *& P, qr_precond_tag)
Definition at line 55 of file accelerated_linearl2_regression_solver_Elemental.hpp.
References utcondest().
Referenced by skylark::algorithms::accelerated_regression_solver_t< regression_problem_t< elem::DistMatrix< ValueType, VD, elem::STAR >, linear_tag, l2_tag, no_reg_tag >, elem::DistMatrix< ValueType, VD, elem::STAR >, elem::DistMatrix< ValueType, elem::STAR, elem::STAR >, simplified_blendenpik_tag< TransformType, PrecondTag > >::accelerated_regression_solver_t(), skylark::algorithms::accelerated_regression_solver_t< regression_problem_t< elem::DistMatrix< ValueType, VD, elem::STAR >, linear_tag, l2_tag, no_reg_tag >, elem::DistMatrix< ValueType, VD, elem::STAR >, elem::DistMatrix< ValueType, elem::STAR, elem::STAR >, blendenpik_tag< PrecondTag > >::accelerated_regression_solver_t(), and skylark::algorithms::accelerated_regression_solver_t< regression_problem_t< elem::DistMatrix< ValueType, VD, elem::STAR >, linear_tag, l2_tag, no_reg_tag >, elem::DistMatrix< ValueType, VD, elem::STAR >, elem::DistMatrix< ValueType, elem::STAR, elem::STAR >, lsrn_tag< PrecondTag > >::accelerated_regression_solver_t().
template<typename SolType , typename SketchType , typename PrecondType > double skylark::algorithms::flinl2_internal::build_precond (SketchType & SA, PrecondType & V, nla::precond_t< SolType > *& P, svd_precond_tag)
Definition at line 65 of file accelerated_linearl2_regression_solver_Elemental.hpp.
References n.
void BLAS() skylark::algorithms::flinl2_internal::dtrcon (const char * norm, const char * uplo, const char * diag, const int * n, const double * A, const int * lda, double * rcond, double * work, int * iwork, int * info)
Referenced by utcondest().
void BLAS() skylark::algorithms::flinl2_internal::strcon (const char * norm, const char * uplo, const char * diag, const int * n, const float * A, const int * lda, float * rcond, float * work, int * iwork, int * info)
Referenced by utcondest().
double skylark::algorithms::flinl2_internal::utcondest (const elem::Matrix< double > & A) [inline]
Definition at line 25 of file accelerated_linearl2_regression_solver_Elemental.hpp.
References dtrcon(), and n.
Referenced by build_precond(), and utcondest().
double skylark::algorithms::flinl2_internal::utcondest (const elem::Matrix< float > & A) [inline]
Definition at line 37 of file accelerated_linearl2_regression_solver_Elemental.hpp.
References n, and strcon().
template<typename T > double skylark::algorithms::flinl2_internal::utcondest (const elem::DistMatrix< T, elem::STAR, elem::STAR > & A) [inline]
Definition at line 50 of file accelerated_linearl2_regression_solver_Elemental.hpp.
References utcondest().