Skylark (Sketching Library): BlockADMMSolver< T > Class Template Reference
BlockADMMSolver< T > Class Template Reference
#include <BlockADMM.hpp>
Public Types
typedef
skylark::sketch::sketch_transform_t
< T, LocalMatrixType > feature_transform_t
typedef std::vector< const
feature_transform_t * > feature_transform_array_t
Public Member Functions
BlockADMMSolver (const lossfunction *loss, const regularization *regularizer, double lambda, int NumFeatures, int NumFeaturePartitions=1)
template<typename Kernel , typename MapTypeTag >
BlockADMMSolver (skylark::base::context_t &context, const lossfunction *loss, const regularization *regularizer, double lambda, int NumFeatures, Kernel kernel, MapTypeTag tag, int NumFeaturePartitions=1)
BlockADMMSolver (const lossfunction *loss, const regularization *regularizer, const feature_transform_array_t &featureMaps, double lambda, bool ScaleFeatureMaps=true)
void set_nthreads (int NumThreads)
void set_rho (double RHO)
void set_maxiter (double MAXITER)
void set_tol (double TOL)
void set_cache_transform (bool CacheTransforms)
~BlockADMMSolver ()
void InitializeFactorizationCache ()
void InitializeTransformCache (int n)
skylark::ml::model_t< T,
LocalMatrixType > * train (T &X, LocalMatrixType &Y, T &Xv, LocalMatrixType &Yv, const boost::mpi::communicator &comm)
int get_numfeatures ()
feature_transform_array_t & get_feature_maps ()
Detailed Description
template<class T>
class BlockADMMSolver< T >
Definition at line 26 of file BlockADMM.hpp.
Member Typedef Documentation
template<class T> typedef std::vector<const feature_transform_t *> BlockADMMSolver< T >::feature_transform_array_t
Definition at line 32 of file BlockADMM.hpp.
template<class T> typedef skylark::sketch::sketch_transform_t<T, LocalMatrixType> BlockADMMSolver< T >::feature_transform_t
Definition at line 31 of file BlockADMM.hpp.
Constructor & Destructor Documentation
template<class T > BlockADMMSolver< T >::BlockADMMSolver (const lossfunction * loss, const regularization * regularizer, double lambda, int NumFeatures, int NumFeaturePartitions = 1)
Definition at line 126 of file BlockADMM.hpp.
References BlockADMMSolver< T >::InitializeFactorizationCache(), and min().
template<class T > template<typename Kernel , typename MapTypeTag > BlockADMMSolver< T >::BlockADMMSolver (skylark::base::context_t & context, const lossfunction * loss, const regularization * regularizer, double lambda, int NumFeatures, Kernel kernel, MapTypeTag tag, int NumFeaturePartitions = 1)
Definition at line 155 of file BlockADMM.hpp.
References BlockADMMSolver< T >::InitializeFactorizationCache(), and min().
template<class T > BlockADMMSolver< T >::BlockADMMSolver (const lossfunction * loss, const regularization * regularizer, const feature_transform_array_t & featureMaps, double lambda, bool ScaleFeatureMaps = true)
Definition at line 187 of file BlockADMM.hpp.
References BlockADMMSolver< T >::InitializeFactorizationCache().
template<class T > BlockADMMSolver< T >::~BlockADMMSolver ()
Definition at line 214 of file BlockADMM.hpp.
Member Function Documentation
template<class T> feature_transform_array_t& BlockADMMSolver< T >::get_feature_maps () [inline]
Definition at line 77 of file BlockADMM.hpp.
template<class T> int BlockADMMSolver< T >::get_numfeatures () [inline]
Definition at line 75 of file BlockADMM.hpp.
template<class T > void BlockADMMSolver< T >::InitializeFactorizationCache ()
Definition at line 102 of file BlockADMM.hpp.
Referenced by BlockADMMSolver< T >::BlockADMMSolver().
template<class T > void BlockADMMSolver< T >::InitializeTransformCache (int n)
Definition at line 113 of file BlockADMM.hpp.
References n.
template<class T> void BlockADMMSolver< T >::set_cache_transform (bool CacheTransforms) [inline]
Definition at line 64 of file BlockADMM.hpp.
Referenced by GetSolver().
template<class T> void BlockADMMSolver< T >::set_maxiter (double MAXITER) [inline]
Definition at line 62 of file BlockADMM.hpp.
Referenced by GetSolver().
template<class T> void BlockADMMSolver< T >::set_nthreads (int NumThreads) [inline]
Definition at line 60 of file BlockADMM.hpp.
Referenced by GetSolver().
template<class T> void BlockADMMSolver< T >::set_rho (double RHO) [inline]
Definition at line 61 of file BlockADMM.hpp.
Referenced by GetSolver().
template<class T> void BlockADMMSolver< T >::set_tol (double TOL) [inline]
Definition at line 63 of file BlockADMM.hpp.
Referenced by GetSolver().
template<class T > skylark::ml::model_t< T, LocalMatrixType > * BlockADMMSolver< T >::train (T & X, LocalMatrixType & Y, T & Xv, LocalMatrixType & Yv, const boost::mpi::communicator & comm)
Definition at line 225 of file BlockADMM.hpp.
References skylark::sketch::sketch_transform_t< InputMatrixType, OutputMatrixType >::apply(), skylark::ml::model_t< InputType, OutputType >::evaluate(), skylark::base::Gemm(), skylark::ml::model_t< InputType, OutputType >::get_coef(), GetNumTargets(), skylark::base::Height(), skylark::ml::model_t< InputType, OutputType >::predict(), SKYLARK_TIMER_ACCUMULATE, SKYLARK_TIMER_INITIALIZE, SKYLARK_TIMER_PRINT, SKYLARK_TIMER_RESTART, and skylark::base::Width().
Referenced by run().
The documentation for this class was generated from the following file:
/var/lib/jenkins/jobs/Skylark/workspace/ml/BlockADMM.hpp