Skylark (Sketching Library): skylark::sketch::FJLT_data_t Struct Reference
skylark::sketch::FJLT_data_t Struct Reference
#include <FJLT_data.hpp>
Classes
struct params_t
Params structure.
Public Types
typedef
boost::random::uniform_int_distribution
< size_t > value_distribution_type
typedef
utility::rademacher_distribution_t
< double > underlying_value_distribution_type
typedef sketch_transform_data_t base_t
Public Member Functions
FJLT_data_t (int N, int S, base::context_t &context)
FJLT_data_t (int N, int S, const params_t &params, base::context_t &context)
FJLT_data_t (const boost::property_tree::ptree &pt)
virtual boost::property_tree::ptree to_ptree () const
Protected Types
typedef RFUT_data_t
< underlying_value_distribution_type > underlying_data_type
Protected Member Functions
FJLT_data_t (int N, int S, const base::context_t &context, std::string type)
base::context_t build ()
Protected Attributes
std::vector< size_t > samples
boost::shared_ptr
< underlying_data_type > underlying_data
Detailed Description
This is the base data class for FJLT. Essentially, it holds the input and sketched matrix sizes, the vector of samples and the data of the underlying transform.
Definition at line 20 of file FJLT_data.hpp.
Member Typedef Documentation
typedef sketch_transform_data_t skylark::sketch::FJLT_data_t::base_t
Definition at line 27 of file FJLT_data.hpp.
typedef RFUT_data_t<underlying_value_distribution_type> skylark::sketch::FJLT_data_t::underlying_data_type [protected]
Definition at line 86 of file FJLT_data.hpp.
typedef utility::rademacher_distribution_t<double> skylark::sketch::FJLT_data_t::underlying_value_distribution_type
Reimplemented in skylark::sketch::FJLT_t< elem::DistMatrix< ValueType, ColDist, elem::STAR >, elem::DistMatrix< ValueType, elem::STAR, elem::STAR > >, and skylark::sketch::FJLT_t< elem::DistMatrix< ValueType, ColDist, elem::STAR >, elem::Matrix< ValueType > >.
Definition at line 25 of file FJLT_data.hpp.
typedef boost::random::uniform_int_distribution<size_t> skylark::sketch::FJLT_data_t::value_distribution_type
Definition at line 23 of file FJLT_data.hpp.
Constructor & Destructor Documentation
skylark::sketch::FJLT_data_t::FJLT_data_t (int N, int S, base::context_t & context) [inline]
Definition at line 34 of file FJLT_data.hpp.
References build().
skylark::sketch::FJLT_data_t::FJLT_data_t (int N, int S, const params_t & params, base::context_t & context) [inline]
Definition at line 41 of file FJLT_data.hpp.
References build().
skylark::sketch::FJLT_data_t::FJLT_data_t (const boost::property_tree::ptree & pt) [inline]
Definition at line 48 of file FJLT_data.hpp.
References build().
skylark::sketch::FJLT_data_t::FJLT_data_t (int N, int S, const base::context_t & context, std::string type) [inline, protected]
Definition at line 70 of file FJLT_data.hpp.
Member Function Documentation
base::context_t skylark::sketch::FJLT_data_t::build () [inline, protected]
random samples should only be drawn here, return context after random samples have been extracted.
Reimplemented from skylark::sketch::sketch_transform_data_t.
Definition at line 76 of file FJLT_data.hpp.
References skylark::sketch::sketch_transform_data_t::_N, skylark::sketch::sketch_transform_data_t::_S, skylark::sketch::sketch_transform_data_t::build(), skylark::base::context_t::generate_random_samples_array(), samples, and underlying_data.
Referenced by FJLT_data_t().
virtual boost::property_tree::ptree skylark::sketch::FJLT_data_t::to_ptree () const [inline, virtual]
Serializes a sketch to a string.
Parameters:
[out] property_tree describing the sketch.
Implements skylark::sketch::sketch_transform_data_t.
Definition at line 62 of file FJLT_data.hpp.
References skylark::sketch::sketch_transform_data_t::add_common().
Member Data Documentation
std::vector<size_t> skylark::sketch::FJLT_data_t::samples [protected]
Vector of samples
Definition at line 88 of file FJLT_data.hpp.
Referenced by build().
boost::shared_ptr<underlying_data_type> skylark::sketch::FJLT_data_t::underlying_data [protected]
Data of the underlying RFUT transformation
Definition at line 90 of file FJLT_data.hpp.
Referenced by build().
The documentation for this struct was generated from the following file:
/var/lib/jenkins/jobs/Skylark/workspace/sketch/FJLT_data.hpp