Skylark (Sketching Library): /var/lib/jenkins/jobs/Skylark/workspace/ml/io.hpp File Reference
/var/lib/jenkins/jobs/Skylark/workspace/ml/io.hpp File Reference
#include <boost/mpi.hpp>
#include <sstream>
#include <cstdlib>
#include <string>
#include <elemental.hpp>
#include "../base/sparse_matrix.hpp"
#include "options.hpp"
#include <H5Cpp.h>
Typedefs
typedef elem::DistMatrix
< double, elem::CIRC,
elem::CIRC > DistCircMatrixType
typedef
skylark::base::sparse_matrix_t
< double > sparse_matrix_t
typedef elem::Matrix< double > LocalMatrixType
Functions
template<typename T >
void read_libsvm (const boost::mpi::communicator &comm, std::string fName, elem::Matrix< T > &Xlocal, elem::Matrix< T > &Ylocal, int min_d=0, int blocksize=10000)
template<typename T >
void read_libsvm (const boost::mpi::communicator &comm, std::string fName, skylark::base::sparse_matrix_t< T > &X, elem::Matrix< T > &Y, int min_d=0)
template<class InputType , class LabelType >
void read (const boost::mpi::communicator &comm, int fileformat, std::string filename, InputType &X, LabelType &Y, int d=0)
void read_model_file (std::string fName, elem::Matrix< double > &W)
std::string read_header (const boost::mpi::communicator &comm, std::string fName)
Typedef Documentation
typedef elem::DistMatrix<double, elem::CIRC, elem::CIRC> DistCircMatrixType
Definition at line 21 of file io.hpp.
typedef elem::Matrix<double> LocalMatrixType
Definition at line 23 of file io.hpp.
typedef skylark::base::sparse_matrix_t<double> sparse_matrix_t
Definition at line 22 of file io.hpp.
Function Documentation
template<class InputType , class LabelType > void read (const boost::mpi::communicator & comm, int fileformat, std::string filename, InputType & X, LabelType & Y, int d = 0)
Definition at line 878 of file io.hpp.
References HDF5_DENSE, HDF5_SPARSE, LIBSVM_DENSE, LIBSVM_SPARSE, and read_libsvm().
Referenced by run().
std::string read_header (const boost::mpi::communicator & comm, std::string fName)
Definition at line 937 of file io.hpp.
template<typename T > void read_libsvm (const boost::mpi::communicator & comm, std::string fName, elem::Matrix< T > & Xlocal, elem::Matrix< T > & Ylocal, int min_d = 0, int blocksize = 10000)
Definition at line 539 of file io.hpp.
References skylark::sketch::blocksize, max(), and t.
Referenced by main(), and read().
template<typename T > void read_libsvm (const boost::mpi::communicator & comm, std::string fName, skylark::base::sparse_matrix_t< T > & X, elem::Matrix< T > & Y, int min_d = 0)
Definition at line 676 of file io.hpp.
References skylark::base::sparse_matrix_t< ValueType >::attach(), max(), and t.
void read_model_file (std::string fName, elem::Matrix< double > & W)
Definition at line 900 of file io.hpp.
References m, and n.
Referenced by main().