Skylark (Sketching Library): /var/lib/jenkins/jobs/Skylark/workspace/examples/lsqr.cpp File Reference
/var/lib/jenkins/jobs/Skylark/workspace/examples/lsqr.cpp File Reference
#include <iostream>
#include <functional>
#include <cstring>
#include <vector>
#include <utility>
#include <ext/hash_map>
#include <elemental.hpp>
#include <CombBLAS.h>
#include <boost/mpi.hpp>
#include <skylark.hpp>
#include "utilities.hpp"
#include "parser.hpp"
Typedefs
typedef std::vector< int > IntContainer
typedef std::vector< double > DblContainer
typedef elem::Matrix< double > DenseMatrixType
typedef elem::DistMatrix< double > DenseDistMatrixType
typedef SpDCCols< int, double > SparseMatrixType
typedef SpParMat< int, double,
SparseMatrixType > SparseDistMatrixType
typedef FullyDistVec< int, double > SparseVectorType
typedef FullyDistMultiVec< int,
double > SparseMultiVectorType
typedef
skyutil::uniform_matrix_t
< DenseDistMatrixType > uni_dense_dist_mat_t
typedef
skyutil::uniform_matrix_t
< SparseDistMatrixType > uni_sparse_dist_mat_t
typedef
skyutil::uniform_matrix_t
< SparseMultiVectorType > uni_sparse_dist_multi_vec_t
typedef
skyutil::empty_matrix_t
< DenseDistMatrixType > empty_dense_dist_mat_t
typedef
skyutil::empty_matrix_t
< SparseDistMatrixType > empty_sparse_dist_mat_t
typedef
skyutil::empty_matrix_t
< SparseMultiVectorType > empty_sparse_dist_multi_vec_t
typedef skyutil::print_t
< SparseDistMatrixType > sparse_dist_mat_printer_t
typedef skyutil::print_t
< SparseMultiVectorType > sparse_dist_multi_vec_printer_t
typedef skyutil::print_t
< DenseDistMatrixType > dense_dist_mat_printer_t
Functions
int main (int argc, char **argv)
Variables
int int_params [NUM_INT_PARAMETERS]
char * chr_params [NUM_CHR_PARAMETERS]
Typedef Documentation
typedef std::vector<double> DblContainer
Definition at line 35 of file lsqr.cpp.
typedef skyutil::print_t<DenseDistMatrixType> dense_dist_mat_printer_t
Definition at line 56 of file lsqr.cpp.
typedef elem::DistMatrix<double> DenseDistMatrixType
Definition at line 37 of file lsqr.cpp.
typedef elem::Matrix<double> DenseMatrixType
Definition at line 36 of file lsqr.cpp.
typedef skyutil::empty_matrix_t<DenseDistMatrixType> empty_dense_dist_mat_t
Definition at line 49 of file lsqr.cpp.
typedef skyutil::empty_matrix_t<SparseDistMatrixType> empty_sparse_dist_mat_t
Definition at line 50 of file lsqr.cpp.
typedef skyutil::empty_matrix_t<SparseMultiVectorType> empty_sparse_dist_multi_vec_t
Definition at line 52 of file lsqr.cpp.
typedef std::vector<int> IntContainer
Typedef DistMatrix and Matrix
Definition at line 34 of file lsqr.cpp.
typedef skyutil::print_t<SparseDistMatrixType> sparse_dist_mat_printer_t
Definition at line 54 of file lsqr.cpp.
typedef skyutil::print_t<SparseMultiVectorType> sparse_dist_multi_vec_printer_t
Definition at line 55 of file lsqr.cpp.
typedef SpParMat<int, double, SparseMatrixType> SparseDistMatrixType
Definition at line 40 of file lsqr.cpp.
typedef SpDCCols<int, double> SparseMatrixType
Definition at line 39 of file lsqr.cpp.
typedef FullyDistMultiVec<int, double> SparseMultiVectorType
Definition at line 42 of file lsqr.cpp.
typedef FullyDistVec<int, double> SparseVectorType
Definition at line 41 of file lsqr.cpp.
typedef skyutil::uniform_matrix_t<DenseDistMatrixType> uni_dense_dist_mat_t
Definition at line 44 of file lsqr.cpp.
typedef skyutil::uniform_matrix_t<SparseDistMatrixType> uni_sparse_dist_mat_t
Definition at line 45 of file lsqr.cpp.
typedef skyutil::uniform_matrix_t<SparseMultiVectorType> uni_sparse_dist_multi_vec_t
Definition at line 47 of file lsqr.cpp.
Function Documentation
int main (int argc, char ** argv)
Only left sketch is supported for now
Only randomization is supported for now
TODO: Read the entries!
Run the test for elemental matrices
Depending on which sketch is requested, do the sketching
Set up the iterative solver parameters
Solve the exact problem
Solve the sketched problem---change to using the sketched regressor
Check the quality of the solution
Finalize Elemental
Run the test for CombBLAS matrices
Depending on which sketch is requested, do the sketching
Set up the iterative solver parameters
Solve the exact problem
Solve the sketched problem
Check the quality of the solution
Definition at line 58 of file lsqr.cpp.
References skylark::sketch::FJLT_t< InputMatrixType, OutputMatrixType >::apply(), skylark::sketch::CWT_t< InputMatrixType, OutputMatrixType >::apply(), skylark::sketch::JLT_t< InputMatrixType, OutputMatrixType >::apply(), chr_params, skylark::sketch::c::FJLT, int_params, and skylark::sketch::c::JLT.
Variable Documentation
char* chr_params[NUM_CHR_PARAMETERS]
Definition at line 31 of file lsqr.cpp.
int int_params[NUM_INT_PARAMETERS]
This file cannot be built without CombBLAS and Elemental both being present. The accompanying CMakeLists.txt checks for both libraries to be available.
Definition at line 30 of file lsqr.cpp.