Skylark (Sketching Library): /var/lib/jenkins/jobs/Skylark/workspace/tests/unit/LocalSparseSketchApply.cpp File Reference
/var/lib/jenkins/jobs/Skylark/workspace/tests/unit/LocalSparseSketchApply.cpp File Reference
#include <vector>
#include <boost/mpi.hpp>
#include <boost/test/minimal.hpp>
#include "../../utility/distributions.hpp"
#include "../../base/sparse_matrix.hpp"
#include "../../sketch/sketch.hpp"
Classes
struct Dummy_t< InputMatrixType, OutputMatrixType >
Functions
int test_main (int argc, char *argv[])
Function Documentation
int test_main (int argc, char * argv[])
Definition at line 46 of file LocalSparseSketchApply.cpp.
References skylark::sketch::hash_transform_t< InputMatrixType, OutputMatrixType, boost::random::uniform_int_distribution, skylark::utility::rademacher_distribution_t >::apply(), Dummy_t< InputMatrixType, OutputMatrixType >::getRowIdx(), Dummy_t< InputMatrixType, OutputMatrixType >::getRowValues(), m, and n.