VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "precise64"
  # The url from where the 'config.vm.box' box will be fetched if not locally available
  config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box"
  # The list of software to install
  config.vm.provision :shell, :path => "bootstrap.sh"
  
  # Increase memory
  config.vm.provider :virtualbox do |vb|                                                                                                                   
    vb.customize ["modifyvm", :id, "--memory", "4096"]                                                                                                     
  end  
end
