Skylark (Sketching Library): skylark::sketch::RFUT_data_t< ValueDistributionType > Struct Template Reference
skylark::sketch::RFUT_data_t< ValueDistributionType > Struct Template Reference
#include <RFUT_data.hpp>
Public Types
typedef ValueDistributionType value_distribution_type
Public Member Functions
RFUT_data_t (int N, skylark::base::context_t &context)
Protected Member Functions
base::context_t build ()
Protected Attributes
int _N
const base::context_t _creation_context
Store the context on creation for serialization.
std::vector< double > D
Detailed Description
template<typename ValueDistributionType>
struct skylark::sketch::RFUT_data_t< ValueDistributionType >
This is the base data class for RFUT transform. Essentially, it holds the input and sketched matrix sizes and the random diagonal part.
Definition at line 22 of file RFUT_data.hpp.
Member Typedef Documentation
template<typename ValueDistributionType > typedef ValueDistributionType skylark::sketch::RFUT_data_t< ValueDistributionType >::value_distribution_type
Reimplemented in skylark::sketch::RFUT_t< elem::DistMatrix< ValueType, RowDist, elem::STAR >, FUT, ValueDistributionType >, and skylark::sketch::RFUT_t< elem::DistMatrix< ValueType, elem::STAR, RowDist >, FUT, ValueDistributionType >.
Definition at line 24 of file RFUT_data.hpp.
Constructor & Destructor Documentation
template<typename ValueDistributionType > skylark::sketch::RFUT_data_t< ValueDistributionType >::RFUT_data_t (int N, skylark::base::context_t & context) [inline]
Regular constructor
Definition at line 29 of file RFUT_data.hpp.
References skylark::sketch::RFUT_data_t< ValueDistributionType >::build().
Member Function Documentation
template<typename ValueDistributionType > base::context_t skylark::sketch::RFUT_data_t< ValueDistributionType >::build () [inline, protected]
Definition at line 45 of file RFUT_data.hpp.
References skylark::sketch::RFUT_data_t< ValueDistributionType >::_creation_context, skylark::sketch::RFUT_data_t< ValueDistributionType >::_N, skylark::sketch::RFUT_data_t< ValueDistributionType >::D, and skylark::base::context_t::generate_random_samples_array().
Referenced by skylark::sketch::RFUT_data_t< ValueDistributionType >::RFUT_data_t().
Member Data Documentation
template<typename ValueDistributionType > const base::context_t skylark::sketch::RFUT_data_t< ValueDistributionType >::_creation_context [protected]
Store the context on creation for serialization.
Definition at line 41 of file RFUT_data.hpp.
Referenced by skylark::sketch::RFUT_data_t< ValueDistributionType >::build().
template<typename ValueDistributionType > int skylark::sketch::RFUT_data_t< ValueDistributionType >::_N [protected]
Input dimension
Definition at line 38 of file RFUT_data.hpp.
Referenced by skylark::sketch::RFUT_data_t< ValueDistributionType >::build().
template<typename ValueDistributionType > std::vector<double> skylark::sketch::RFUT_data_t< ValueDistributionType >::D [protected]
Diagonal part
Definition at line 43 of file RFUT_data.hpp.
Referenced by skylark::sketch::RFUT_data_t< ValueDistributionType >::build().
The documentation for this struct was generated from the following file:
/var/lib/jenkins/jobs/Skylark/workspace/sketch/RFUT_data.hpp