if (SKYLARK_HAVE_FFTW)
  set(OPTIONAL_LIBS "${FFTW_LIBRARY};${OPTIONAL_LIBS}")
endif (SKYLARK_HAVE_FFTW)

if (SKYLARK_HAVE_FFTWF)
  set(OPTIONAL_LIBS "${FFTWF_LIBRARY};${OPTIONAL_LIBS}")
endif (SKYLARK_HAVE_FFTWF)

if (SKYLARK_HAVE_COMBBLAS)
  set(OPTIONAL_LIBS "${CombBLAS_LIBRARIES};${OPTIONAL_LIBS}")
endif (SKYLARK_HAVE_COMBBLAS)

if (SKYLARK_HAVE_HDF5)
  set(OPTIONAL_LIBS "${HDF5_LIBRARIES};${ZLIB_LIBRARIES};${OPTIONAL_LIBS}")
endif (SKYLARK_HAVE_HDF5)

if (SKYLARK_HAVE_LIBHDFS)
  set(OPTIONAL_LIBS "${LIBHDFS_LIBRARIES};${JAVA_JVM_LIBRARY};${OPTIONAL_LIBS}")
endif (SKYLARK_HAVE_LIBHDFS)

if (Boost_FILESYSTEM_FOUND)
  set(OPTIONAL_LIBS "${Boost_FILESYSTEM_LIBRARY};${OPTIONAL_LIBS}")
endif (Boost_FILESYSTEM_FOUND)
