Skylark (Sketching Library): /var/lib/jenkins/jobs/Skylark/workspace/examples/elemental.cpp File Reference
/var/lib/jenkins/jobs/Skylark/workspace/examples/elemental.cpp File Reference
#include <iostream>
#include <functional>
#include <cstring>
#include <vector>
#include <utility>
#include <ext/hash_map>
#include <elemental.hpp>
#include <boost/mpi.hpp>
#include <skylark.hpp>
#include "utilities.hpp"
#include "parser.hpp"
Typedefs
typedef std::vector< int > IntContainer
typedef std::vector< double > DblContainer
typedef elem::Matrix< double > MatrixType
typedef elem::DistMatrix
< double, elem::VC, elem::STAR > DistMatrixType
Functions
int main (int argc, char **argv)
Variables
int int_params [NUM_INT_PARAMETERS]
char * chr_params [NUM_CHR_PARAMETERS]
Typedef Documentation
typedef std::vector<double> DblContainer
Definition at line 27 of file elemental.cpp.
typedef elem::DistMatrix<double, elem::VC, elem::STAR> DistMatrixType
Definition at line 29 of file elemental.cpp.
typedef std::vector<int> IntContainer
Typedef DistMatrix and Matrix
Definition at line 26 of file elemental.cpp.
typedef elem::Matrix<double> MatrixType
Definition at line 28 of file elemental.cpp.
Function Documentation
int main (int argc, char ** argv)
Only randomization is supported for now
TODO: Read the entries!
Depending on which sketch is requested, do the sketching.
TODO: Do that same to B, and solve the system!
TODO: Do that same to B, and solve the system!
TODO: Do that same to B, and solve the system!
Definition at line 31 of file elemental.cpp.
References skylark::sketch::FJLT_t< InputMatrixType, OutputMatrixType >::apply(), skylark::sketch::CWT_t< InputMatrixType, OutputMatrixType >::apply(), skylark::sketch::JLT_t< InputMatrixType, OutputMatrixType >::apply(), chr_params, skylark::sketch::c::FJLT, int_params, skylark::sketch::c::JLT, SKYLARK_BEGIN_TRY, SKYLARK_CATCH_AND_RETURN_ERROR_CODE, SKYLARK_END_TRY, SKYLARK_PRINT_EXCEPTION_DETAILS, SKYLARK_PRINT_EXCEPTION_TRACE, and skylark_strerror().
Variable Documentation
char* chr_params[NUM_CHR_PARAMETERS]
Definition at line 23 of file elemental.cpp.
Referenced by main().
int int_params[NUM_INT_PARAMETERS]
Definition at line 22 of file elemental.cpp.
Referenced by main().