Skylark (Sketching Library): skylark::sketch::CWT_data_t Struct Reference
skylark::sketch::CWT_data_t Struct Reference
#include <CWT_data.hpp>
Classes
struct params_t
Params structure.
Public Types
typedef hash_transform_data_t
< boost::random::uniform_int_distribution,
utility::rademacher_distribution_t > base_t
Public Member Functions
CWT_data_t (int N, int S, base::context_t &context)
CWT_data_t (int N, int S, const params_t &params, base::context_t &context)
CWT_data_t (const boost::property_tree::ptree &pt)
virtual boost::property_tree::ptree to_ptree () const
Protected Member Functions
CWT_data_t (int N, int S, const base::context_t &context, std::string type)
Detailed Description
Clarkson-Woodruff Transform (data)
Clarkson-Woodruff Transform is essentially the CountSketch sketching originally suggested by Charikar et al. Analysis by Clarkson and Woodruff in STOC 2013 shows that this is sketching scheme can be used to build a subspace embedding.
CWT was additionally analyzed by Meng and Mahoney (STOC'13) and is equivalent to OSNAP with s=1.
Definition at line 23 of file CWT_data.hpp.
Member Typedef Documentation
typedef hash_transform_data_t< boost::random::uniform_int_distribution, utility::rademacher_distribution_t > skylark::sketch::CWT_data_t::base_t
Reimplemented from skylark::sketch::hash_transform_data_t< boost::random::uniform_int_distribution, utility::rademacher_distribution_t >.
Definition at line 29 of file CWT_data.hpp.
Constructor & Destructor Documentation
skylark::sketch::CWT_data_t::CWT_data_t (int N, int S, base::context_t & context) [inline]
Definition at line 36 of file CWT_data.hpp.
References skylark::sketch::hash_transform_data_t< boost::random::uniform_int_distribution, utility::rademacher_distribution_t >::build().
skylark::sketch::CWT_data_t::CWT_data_t (int N, int S, const params_t & params, base::context_t & context) [inline]
Definition at line 42 of file CWT_data.hpp.
References skylark::sketch::hash_transform_data_t< boost::random::uniform_int_distribution, utility::rademacher_distribution_t >::build().
skylark::sketch::CWT_data_t::CWT_data_t (const boost::property_tree::ptree & pt) [inline]
Definition at line 48 of file CWT_data.hpp.
References skylark::sketch::hash_transform_data_t< boost::random::uniform_int_distribution, utility::rademacher_distribution_t >::build().
skylark::sketch::CWT_data_t::CWT_data_t (int N, int S, const base::context_t & context, std::string type) [inline, protected]
Definition at line 69 of file CWT_data.hpp.
Member Function Documentation
virtual boost::property_tree::ptree skylark::sketch::CWT_data_t::to_ptree () const [inline, virtual]
Serializes a sketch to a Boost property tree. This can be conveniently converted to other formats, e.g. to JSON and XML.
Parameters:
[out] property_tree describing the sketch.
Reimplemented from skylark::sketch::hash_transform_data_t< boost::random::uniform_int_distribution, utility::rademacher_distribution_t >.
Definition at line 61 of file CWT_data.hpp.
References skylark::sketch::sketch_transform_data_t::add_common().
The documentation for this struct was generated from the following file:
/var/lib/jenkins/jobs/Skylark/workspace/sketch/CWT_data.hpp