VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "trusty64"
  # The url from where the 'config.vm.box' box will be fetched if not locally available
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
  # The list of software to install
  config.vm.provision :shell, :path => "bootstrap.sh"
  # Forward a port to the ipython notebook
  config.vm.network :forwarded_port, host: 6868, guest: 8888

  # Increase memory
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "4096"]
  end
end
